# Quantitative Momentum Strategy

"Momentum investing" means investing in the stocks that have increased in price the most.

For this project, we're going to build an investing strategy that selects the 50 stocks with the highest price momentum. From there, we will calculate recommended trades for an equal-weight portfolio of these 50 stocks.


## Library Imports

The first thing we need to do is import the open-source software libraries that we'll be using in this tutorial.

In [1]:
import numpy as np
import pandas as pd
import requests
import math
from scipy.stats import percentileofscore as score
import xlsxwriter

## Importing Our List of Stocks

As before, we'll need to import our list of stocks and our API token before proceeding. Make sure the `.csv` file is still in your working directory and import it with the following command:

In [2]:
stocks = pd.read_csv('sp_500_stocks.csv')
from secrets import IEX_CLOUD_API_TOKEN

## Making Our First API Call

It's now time to make the first version of our momentum screener!

We need to get one-year price returns for each stock in the universe. Here's how.

In [3]:
symbol = 'AAPL'
api_url = f'https://sandbox.iexapis.com/stable/stock/{symbol}/stats?token={IEX_CLOUD_API_TOKEN}'
data = requests.get(api_url).json()
# data.status_code
data

{'companyName': 'Apple Inc',
 'marketcap': 2748133954546,
 'week52high': 190.79,
 'week52low': 117.64,
 'week52highSplitAdjustOnly': 190.12,
 'week52lowSplitAdjustOnly': 120.72,
 'week52change': 0.3026087472496092,
 'sharesOutstanding': 16834850896,
 'float': 0,
 'avg10Volume': 73560145,
 'avg30Volume': 100891377,
 'day200MovingAvg': 163.09,
 'day50MovingAvg': 176.62,
 'employees': 147725,
 'ttmEPS': 6.19,
 'ttmDividendRate': 0.8801265047053507,
 'dividendYield': 0.005503042904913337,
 'nextDividendDate': '',
 'exDividendDate': '2022-01-26',
 'nextEarningsDate': '2022-04-22',
 'peRatio': 28.213565062346564,
 'beta': 1.333734069599714,
 'maxChangePercent': 64.67324042920211,
 'year5ChangePercent': 4.333273711239397,
 'year2ChangePercent': 1.11956722315118,
 'year1ChangePercent': 0.3068754787177858,
 'ytdChangePercent': -0.05820444159006901,
 'month6ChangePercent': 0.1324105170090473,
 'month3ChangePercent': 0.04457099300026686,
 'month1ChangePercent': 0.01847851139588871,
 'day30ChangePercent': 0.032471998960586265,
 'day5ChangePercent': -0.008150401152912365}

## Parsing Our API Call

This API call has all the information we need. We can parse it using the same square-bracket notation as in the first project of this course. Here is an example.

In [4]:
data['year1ChangePercent']

0.3068754787177858

## Executing A Batch API Call & Building Our DataFrame

Just like in our first project, it's now time to execute several batch API calls and add the information we need to our DataFrame.

We'll start by running the following code cell, which contains some code we already built last time that we can re-use for this project. More specifically, it contains a function called `chunks` that we can use to divide our list of securities into groups of 100.

In [5]:
# Function sourced from 
# https://stackoverflow.com/questions/312443/how-do-you-split-a-list-into-evenly-sized-chunks
def chunks(lst, n):
    """Yield successive n-sized chunks from lst."""
    for i in range(0, len(lst), n):
        yield lst[i:i + n]   
        
symbol_groups = list(chunks(stocks['Ticker'], 100))
symbol_strings = []
for i in range(0, len(symbol_groups)):
    symbol_strings.append(','.join(symbol_groups[i]))
#     print(symbol_strings[i])

my_columns = ['Ticker', 'Price', 'One-Year Price Return', 'Number of Shares to Buy']

Now we need to create a blank DataFrame and add our data to the data frame one-by-one.

In [6]:
final_dataframe = pd.DataFrame(columns = my_columns)

for symbol_string in symbol_strings:
    batch_api_call_url = f'https://sandbox.iexapis.com/stable/stock/market/batch/?types=stats,quote&symbols={symbol_string}&token={IEX_CLOUD_API_TOKEN}'
    data = requests.get(batch_api_call_url).json()
#     print(data['AAPL']['stats'])
    for symbol in symbol_string.split(','):
        if symbol == 'VIAC':
            final_dataframe = final_dataframe.append(
                pd.Series(
                    [
                        symbol,
                        0,
                        0,
                        'N/A'
                    ],
                    index = my_columns),
                ignore_index = True
            )
        elif symbol == 'WLTW':
            final_dataframe = final_dataframe.append(
                pd.Series(
                    [
                        symbol,
                        0,
                        0,
                        'N/A'
                    ],
                    index = my_columns),
                ignore_index = True
            )
        else:
            final_dataframe = final_dataframe.append(
                pd.Series(
                    [
                        symbol,
                        data[symbol]['quote']['latestPrice'],
                        data[symbol]['stats']['year1ChangePercent'],
                        'N/A'
                    ],
                    index = my_columns),
                ignore_index = True
            )
final_dataframe

    Ticker   Price One-Year Price Return Number of Shares to Buy
0        A  137.03               0.04689                     N/A
1      AAL   18.09             -0.044464                     N/A
2      AAP  224.30               0.35523                     N/A
3     AAPL  171.60              0.304385                     N/A
4     ABBV  148.25               0.44006                     N/A
..     ...     ...                   ...                     ...
500    YUM  129.50              0.223592                     N/A
501    ZBH  123.24             -0.234151                     N/A
502   ZBRA  436.98             -0.145411                     N/A
503   ZION   72.39              0.417065                     N/A
504    ZTS  200.61              0.208828                     N/A

[505 rows x 4 columns]

## Removing Low-Momentum Stocks

The investment strategy that we're building seeks to identify the 50 highest-momentum stocks in the S&P 500.

Because of this, the next thing we need to do is remove all the stocks in our DataFrame that fall below this momentum threshold. We'll sort the DataFrame by the stocks' one-year price return, and drop all stocks outside the top 50.

In [7]:
final_dataframe.sort_values('One-Year Price Return', ascending=False, inplace=True)
final_dataframe = final_dataframe[:50]
final_dataframe.reset_index(inplace=True)
final_dataframe

    index Ticker    Price One-Year Price Return Number of Shares to Buy
0     275     LB    82.61              2.313935                     N/A
1     148    DVN    55.97              1.819815                     N/A
2     317    MRO    22.07              1.412328                     N/A
3     344    NUE   128.92              1.174296                     N/A
4     175   FANG   136.17              1.093315                     N/A
5     109    COP    93.45              0.930274                     N/A
6     160    EOG   113.45              0.883434                     N/A
7     386    PXD   235.67              0.848461                     N/A
8     195   FTNT   314.53              0.811252                     N/A
9     299   MCHP    73.21               0.80846                     N/A
10     42    APA    33.34              0.684382                     N/A
11     89     CF    74.47              0.648116                     N/A
12     37   ANET   130.16              0.631957                     N/A
13    212    HAL    33.86              0.630412                     N/A
14    408    SEE    69.99              0.617664                     N/A
15    173    EXR   195.50              0.616819                     N/A
16     54    AZO  1967.80              0.612787                     N/A
17    174      F    18.85              0.595527                     N/A
18    345   NVDA   242.07              0.594789                     N/A
19    465    VAR   182.70              0.590885                     N/A
20    251     IT   293.24              0.580822                     N/A
21    314    MOS    45.00              0.575434                     N/A
22    412    SLB    41.73              0.573627                     N/A
23    496    XOM    80.58              0.572656                     N/A
24    395    RHI   126.10              0.565594                     N/A
25    357    OXY    40.97              0.560415                     N/A
26    300    MCK   278.58              0.556657                     N/A
27    295    MAA   206.53               0.54149                     N/A
28     39   ANTM   468.00              0.535395                     N/A
29    315    MPC    77.04              0.527941                     N/A
30    382    PSA   353.93              0.524186                     N/A
31    273    KSU   298.64              0.513239                     N/A
32    122    CVS   107.01              0.508241                     N/A
33     18    AIG    64.43              0.508145                     N/A
34     98    CMA    99.37              0.503368                     N/A
35    218    HES    97.84              0.499593                     N/A
36     53    AXP   202.83              0.495763                     N/A
37    482    WFC    57.76              0.495228                     N/A
38    259   JNPR    34.40              0.492601                     N/A
39    245    IPG    36.87              0.476147                     N/A
40    170    EXC    41.73              0.475873                     N/A
41    365    PFE    49.05               0.47485                     N/A
42    355   ORLY   684.98              0.472347                     N/A
43    458    UNH   474.63              0.472117                     N/A
44    123    CVX   136.18              0.467383                     N/A
45    110   COST   518.20              0.459995                     N/A
46     19    AIV     6.99              0.459915                     N/A
47    185   FITB    48.98               0.45155                     N/A
48    220    HIG    72.80              0.451097                     N/A
49    352    OKE    64.79              0.445373                     N/A

## Calculating the Number of Shares to Buy

Just like in the last project, we now need to calculate the number of shares we need to buy. The one change we're going to make is wrapping this functionality inside a function, since we'll be using it again later in this Jupyter Notebook.

Since we've already done most of the work on this, try to complete the following two code cells without watching me do it first!

In [8]:
def portfolio_input():
    global portfolio_size
    portfolio_size = input('Enter the size of your portfolio:')
    
    try:
        float(portfolio_size)
    except:
        print('That is not a number! \nPlease try again:')
        portfolio_size = input('Enter the size of your portfolio:')
        
portfolio_input()
print(portfolio_size)

Enter the size of your portfolio:100000
100000

In [9]:
position_size = float(portfolio_size)/len(final_dataframe.index)
for i in range(0, len(final_dataframe)):
    final_dataframe.loc[i, 'Number of Shares to Buy'] = math.floor(position_size/final_dataframe.loc[i, 'Price'])

final_dataframe

D:\Programy\Anaconda\lib\site-packages\pandas\core\indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

    index Ticker    Price One-Year Price Return Number of Shares to Buy
0     275     LB    82.61              2.313935                      24
1     148    DVN    55.97              1.819815                      35
2     317    MRO    22.07              1.412328                      90
3     344    NUE   128.92              1.174296                      15
4     175   FANG   136.17              1.093315                      14
5     109    COP    93.45              0.930274                      21
6     160    EOG   113.45              0.883434                      17
7     386    PXD   235.67              0.848461                       8
8     195   FTNT   314.53              0.811252                       6
9     299   MCHP    73.21               0.80846                      27
10     42    APA    33.34              0.684382                      59
11     89     CF    74.47              0.648116                      26
12     37   ANET   130.16              0.631957                      15
13    212    HAL    33.86              0.630412                      59
14    408    SEE    69.99              0.617664                      28
15    173    EXR   195.50              0.616819                      10
16     54    AZO  1967.80              0.612787                       1
17    174      F    18.85              0.595527                     106
18    345   NVDA   242.07              0.594789                       8
19    465    VAR   182.70              0.590885                      10
20    251     IT   293.24              0.580822                       6
21    314    MOS    45.00              0.575434                      44
22    412    SLB    41.73              0.573627                      47
23    496    XOM    80.58              0.572656                      24
24    395    RHI   126.10              0.565594                      15
25    357    OXY    40.97              0.560415                      48
26    300    MCK   278.58              0.556657                       7
27    295    MAA   206.53               0.54149                       9
28     39   ANTM   468.00              0.535395                       4
29    315    MPC    77.04              0.527941                      25
30    382    PSA   353.93              0.524186                       5
31    273    KSU   298.64              0.513239                       6
32    122    CVS   107.01              0.508241                      18
33     18    AIG    64.43              0.508145                      31
34     98    CMA    99.37              0.503368                      20
35    218    HES    97.84              0.499593                      20
36     53    AXP   202.83              0.495763                       9
37    482    WFC    57.76              0.495228                      34
38    259   JNPR    34.40              0.492601                      58
39    245    IPG    36.87              0.476147                      54
40    170    EXC    41.73              0.475873                      47
41    365    PFE    49.05               0.47485                      40
42    355   ORLY   684.98              0.472347                       2
43    458    UNH   474.63              0.472117                       4
44    123    CVX   136.18              0.467383                      14
45    110   COST   518.20              0.459995                       3
46     19    AIV     6.99              0.459915                     286
47    185   FITB    48.98               0.45155                      40
48    220    HIG    72.80              0.451097                      27
49    352    OKE    64.79              0.445373                      30

## Building a Better (and More Realistic) Momentum Strategy

Real-world quantitative investment firms differentiate between "high quality" and "low quality" momentum stocks:

* High-quality momentum stocks show "slow and steady" outperformance over long periods of time
* Low-quality momentum stocks might not show any momentum for a long time, and then surge upwards.

The reason why high-quality momentum stocks are preferred is because low-quality momentum can often be cause by short-term news that is unlikely to be repeated in the future (such as an FDA approval for a biotechnology company).

To identify high-quality momentum, we're going to build a strategy that selects stocks from the highest percentiles of: 

* 1-month price returns
* 3-month price returns
* 6-month price returns
* 1-year price returns

Let's start by building our DataFrame. You'll notice that I use the abbreviation `hqm` often. It stands for `high-quality momentum`.

In [10]:
hqm_columns = [
    'Ticker',
    'Price',
    'Number of Shares to Buy',
    'One-Year Price Return',
    'One-Year Return Percentile',
    'Six-Month Price Return',
    'Six-Month Return Percentile',
    'Three-Month Price Return',
    'Three-Month Return Percentile',
    'One-Month Price Return',
    'One-Month Return Percentile',
    'HQM Score'
]

hqm_dataframe = pd.DataFrame(columns = hqm_columns)

for symbol_string in symbol_strings:
    batch_api_call_url = f'https://sandbox.iexapis.com/stable/stock/market/batch/?types=stats,quote&symbols={symbol_string}&token={IEX_CLOUD_API_TOKEN}'
    data = requests.get(batch_api_call_url).json()
    for symbol in symbol_string.split(','):
        if symbol == 'VIAC':
            hqm_dataframe = hqm_dataframe.append(
            pd.Series(
            [
                symbol,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            ],
                index = hqm_columns),
                ignore_index=True
            )
        elif symbol == 'WLTW':
            hqm_dataframe = hqm_dataframe.append(
            pd.Series(
            [
                symbol,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            ],
                index = hqm_columns),
                ignore_index=True
            )
        else:
            hqm_dataframe = hqm_dataframe.append(
            pd.Series(
            [
                symbol,
                data[symbol]['quote']['latestPrice'],
                'N/A',
                data[symbol]['stats']['year1ChangePercent'],
                'N/A',
                data[symbol]['stats']['month6ChangePercent'],
                'N/A',
                data[symbol]['stats']['month3ChangePercent'],
                'N/A',
                data[symbol]['stats']['month1ChangePercent'],
                'N/A',
                'N/A'
            ],
                index = hqm_columns),
                ignore_index=True
            )
            
hqm_dataframe

,Ticker,Price,Number of Shares to Buy,One-Year Price Return,One-Year Return Percentile,Six-Month Price Return,Six-Month Return Percentile,Three-Month Price Return,Three-Month Return Percentile,One-Month Price Return,One-Month Return Percentile,HQM Score
0,A,132.83,N/A,0.046701,N/A,-0.220394,N/A,-0.196858,N/A,-0.053845,N/A,N/A
1,AAL,18.22,N/A,-0.044963,N/A,-0.035444,N/A,-0.075345,N/A,0.067821,N/A,N/A
2,AAP,224.50,N/A,0.342597,N/A,0.05524,N/A,-0.045007,N/A,-0.046846,N/A,N/A
3,AAPL,173.30,N/A,0.297074,N/A,0.136423,N/A,0.044045,N/A,0.018616,N/A,N/A
4,ABBV,144.66,N/A,0.449377,N/A,0.246167,N/A,0.261196,N/A,0.085435,N/A,N/A
...,...,...,...,...,...,...,...,...,...,...,...,...
500,YUM,125.90,N/A,0.217678,N/A,-0.055427,N/A,-0.000608,N/A,0.023115,N/A,N/A
501,ZBH,124.86,N/A,-0.23342,N/A,-0.168499,N/A,-0.061162,N/A,-0.017089,N/A,N/A
502,ZBRA,429.37,N/A,-0.147765,N/A,-0.277206,N/A,-0.306426,N/A,-0.162034,N/A,N/A
503,ZION,71.61,N/A,0.419058,N/A,0.336879,N/A,0.08973,N/A,0.108993,N/A,N/A
504,ZTS,200.24,N/A,0.204274,N/A,-0.075525,N/A,-0.15372,N/A,-0.054787,N/A,N/A

## Calculating Momentum Percentiles

We now need to calculate momentum percentile scores for every stock in the universe. More specifically, we need to calculate percentile scores for the following metrics for every stock:

* `One-Year Price Return`
* `Six-Month Price Return`
* `Three-Month Price Return`
* `One-Month Price Return`

Here's how we'll do this:

In [11]:
time_periods = [
    'One-Year',
    'Six-Month',
    'Three-Month',
    'One-Month'
]

# hqm_dataframe.dropna(inplace=True)

hqm_dataframe = hqm_dataframe.fillna(value = np.nan)

for row in hqm_dataframe.index:
    for time_period in time_periods:
        change_col = f'{time_period} Price Return'
        percentile_col = f'{time_period} Return Percentile'
        hqm_dataframe.loc[row, percentile_col] = score(hqm_dataframe[change_col], hqm_dataframe.loc[row, change_col])

hqm_dataframe

,Ticker,Price,Number of Shares to Buy,One-Year Price Return,One-Year Return Percentile,Six-Month Price Return,Six-Month Return Percentile,Three-Month Price Return,Three-Month Return Percentile,One-Month Price Return,One-Month Return Percentile,HQM Score
0,A,132.83,N/A,0.046701,32.871287,-0.220394,6.930693,-0.196858,9.306931,-0.053845,26.930693,N/A
1,AAL,18.22,N/A,-0.044963,18.415842,-0.035444,40.792079,-0.075345,37.425743,0.067821,85.544554,N/A
2,AAP,224.50,N/A,0.342597,81.386139,0.055240,62.376238,-0.045007,43.960396,-0.046846,29.306931,N/A
3,AAPL,173.30,N/A,0.297074,74.851485,0.136423,79.80198,0.044045,66.336634,0.018616,67.524752,N/A
4,ABBV,144.66,N/A,0.449377,89.306931,0.246167,89.70297,0.261196,95.247525,0.085435,90.09901,N/A
...,...,...,...,...,...,...,...,...,...,...,...,...
500,YUM,125.90,N/A,0.217678,62.772277,-0.055427,36.039604,-0.000608,52.673267,0.023115,69.306931,N/A
501,ZBH,124.86,N/A,-0.233420,4.752475,-0.168499,13.069307,-0.061162,40.990099,-0.017089,45.346535,N/A
502,ZBRA,429.37,N/A,-0.147765,8.910891,-0.277206,3.366337,-0.306426,2.970297,-0.162034,1.386139,N/A
503,ZION,71.61,N/A,0.419058,88.712871,0.336879,92.871287,0.089730,75.247525,0.108993,93.861386,N/A
504,ZTS,200.24,N/A,0.204274,60.0,-0.075525,30.891089,-0.153720,18.811881,-0.054787,26.336634,N/A

## Calculating the HQM Score

We'll now calculate our `HQM Score`, which is the high-quality momentum score that we'll use to filter for stocks in this investing strategy.

The `HQM Score` will be the arithmetic mean of the 4 momentum percentile scores that we calculated in the last section.

To calculate arithmetic mean, we will use the `mean` function from Python's built-in `statistics` module.

In [12]:
from statistics import mean

for row in hqm_dataframe.index:
    momentum_percentiles = []
    for time_period in time_periods:
        momentum_percentiles.append(hqm_dataframe.loc[row, f'{time_period} Return Percentile'])
    hqm_dataframe.loc[row, 'HQM Score'] = mean(momentum_percentiles)

## Selecting the 50 Best Momentum Stocks

As before, we can identify the 50 best momentum stocks in our universe by sorting the DataFrame on the `HQM Score` column and dropping all but the top 50 entries.

## Calculating the Number of Shares to Buy

We'll use the `portfolio_input` function that we created earlier to accept our portfolio size. Then we will use similar logic in a `for` loop to calculate the number of shares to buy for each stock in our investment universe.

## Formatting Our Excel Output

We will be using the XlsxWriter library for Python to create nicely-formatted Excel files.

XlsxWriter is an excellent package and offers tons of customization. However, the tradeoff for this is that the library can seem very complicated to new users. Accordingly, this section will be fairly long because I want to do a good job of explaining how XlsxWriter works.

## Creating the Formats We'll Need For Our .xlsx File

You'll recall from our first project that formats include colors, fonts, and also symbols like % and $. We'll need four main formats for our Excel document:

* String format for tickers
* \$XX.XX format for stock prices
* \$XX,XXX format for market capitalization
* Integer format for the number of shares to purchase

Since we already built our formats in the last section of this course, I've included them below for you. Run this code cell before proceeding.

In [ ]:
background_color = '#0a0a23'
font_color = '#ffffff'

string_template = writer.book.add_format(
        {
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

dollar_template = writer.book.add_format(
        {
            'num_format':'$0.00',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

integer_template = writer.book.add_format(
        {
            'num_format':'0',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

percent_template = writer.book.add_format(
        {
            'num_format':'0.0%',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

## Saving Our Excel Output

As before, saving our Excel output is very easy: